name: Deploy

on:
  push:
    branches:
      - main
      - 'hotfix/**'
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: 'Tag para rollback'
        required: false
        default: ''

jobs:
  version:
    if: github.event_name == 'push'
    permissions:
      contents: write
    uses: gi-brrd-test/dp-code-ci-cd/.github/workflows/version.yml@main
    secrets: inherit

  deploy:
    needs: [version]
    if: always() && (needs.version.result == 'success' || needs.version.result == 'skipped')
    uses: gi-brrd-test/dp-code-ci-cd/.github/workflows/deploy-metodo.yml@main
    with:
      rollback_tag: ${{ inputs.rollback_tag || '' }}
    secrets: inherit
