name: Deploy

on:
  push:
    branches:
      - main
      - 'hotfix/**'
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: 'Tag para rollback'
        required: false
        default: ''

jobs:
  deploy:
    uses: gi-brrd-test/dp-code-ci-cd/.github/workflows/deploy-metodo.yml@main
    with:
      rollback_tag: ${{ inputs.rollback_tag || '' }}
    secrets: inherit
